name: Metrics
on:
  # Schedule updates (each day at 12:00am)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: morrisonbrett
          template: classic
          base: header, activity, community, repositories, metadata
          config_display: large
          config_timezone: America/Los_Angeles
          config_twemoji: yes

          # Activities plugin
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: all

          # Achievement plugin
          plugin_achievements: yes
          plugin_achievements_only: >-
            polyglot, stargazer, sponsor, deployer, member, maintainer, developer,
            scripter, packager, explorer, infographile, manager
          plugin_achievements_display: compact
          plugin_achievements_threshold: X

          # People plugin
          plugin_people: yes
          plugin_people_limit: 100
          plugin_people_shuffle: yes
          plugin_people_size: 28
          plugin_people_types: followers

          # Isocalendar plugin
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          # Languages plugin
          plugin_languages: yes

          
